### PR TITLE
Update rebar aecuckooprebuilt plugin

### PR DESCRIPTION
**Pull request by jur0**
This needs to be merged before https://github.com/aeternity/aeternity/pull/2138

### CODE REVIEW

**Comment by ThomasArts** [comment]
Sorry for my ignorance, but why do we need a rebar3 binary in this repository?

**Comment by jur0** [comment]
Because I want to build the aeminer without having to use it as a dependency of the ae node. There are also some tests, dialyzer, etc. Also I want to use a specific version of rebar in this repo.

**Comment by tolbrino** [comment]
In that case you should use the rebar3 version from aeternity itself, because this project will need win32 build support as well.

**Comment by jur0** [comment]
The rebar's version I'm trying to update to in this PR is: `rebar 3.9.0 on Erlang/OTP 20 Erts 9.3.3.3`

**Comment by tolbrino** [comment]
> The rebar's version I'm trying to update to in this PR is: `rebar 3.9.0 on Erlang/OTP 20 Erts 9.3.3.3`

As I said, that version has limited Windows support which might be needed though. So please use the version from aeternity.

**Review by hanssv — APPROVED** [review]

**Review by tolbrino — APPROVED** [review]

**Pull request merged**
